# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Smart_Door',
                'doc_host': 'https://7danielluna7.github.io',
                'git_url': 'https://github.com/7danielluna7/Smart_Door',
                'lib_path': 'Smart_Door'},
  'syms': {'Smart_Door.core': {'Smart_Door.core.foo': ('core.html#foo', 'Smart_Door/core.py')}}}
